### ISSUE TITLE
Widget not fully hidden

### ISSUE THREAD

**Issue by abdullahIsa** [ann0nip/react-whatsapp-widget#16]
Hello, I am having an issue with the widget, I noticed when closed it's open but not open, this causes certain parts of the page to be unclickable or clicking into the widget view, how to fix this? thanks.

![Screenshot (5)](https://user-images.githubusercontent.com/49385380/159201907-f5777782-38e5-446b-a639-95550961d449.png)

**Comment by abdullahIsa** [comment]
I fixed it by overriding the CSS, thanks.

`transform: translateY(150%);`

**Comment by abdullahIsa** [comment]
This issue still happening, thought i fixed it or was fixed, I also noticed the same type has been issue before #6 , how to get this fixed? thanks.

**Comment by ann0nip** [comment]
I just upload some changes to the npm package.

Try to uninstall and install again via `npm install --save react-whatsapp-widget` or using `yarn`

Let me know if that fix the issue.

**Comment by abdullahIsa** [comment]
> I just upload some changes to the npm package.
> 
> Try to uninstall and install again via `npm install --save react-whatsapp-widget` or using `yarn`
> 
> Let me know if that fix the issue.

Hello, thanks very much and yes working now but i also had to override some CSS.

Also would be great to be able to change the Icon in the header, I don't see how to change it in the index.js, thanks very much.

![image](https://user-images.githubusercontent.com/49385380/159296410-8d5da7ef-30bc-4579-9512-e81c55909ff7.png)

**Comment by abdullahIsa** [comment]
> Yeah, the widget is not very modular, I'm aware of that :/
> 
> The icon is a _react-icons_ , yo will see the import in the Header.js file
> 
> `import { BiSupport } from 'react-icons/bi'`

Thanks for the guide and ya this package can progress better, keep up the great work, and thanks a lot.
