### ISSUE TITLE
Outdated peer dependency

### ISSUE THREAD

**Issue by vaxr** [ann0nip/react-whatsapp-widget#21]
Client build without `--legacy-peer-deps` currently breaks if you use any newer React version than 16.
I have been using the widget with React 17 for a while, and it's working fine. I'm confident it should work with React 18 as well.
Would you consider allowing versions 17 and 18 as peer dependencies?

Thanks!

**Comment by ann0nip** [comment]
Hello! This was a hard one, a lot of conflicts between dependencies 🥵
But, it looks like we are good to go with updated dependencies 🚀

Thanks for the report.
