### ISSUE TITLE
Wrong readme.md "Customization" info

### ISSUE THREAD

**Issue by vitorregisrr** [ann0nip/react-whatsapp-widget#22]
Hey! Thank you for this widget. 

When I was trying to customize that in my application, the button was not being customized with "sendButton" prop, and also there wasn't any prop to customize the input placeholder.

So I opened the widget code and saw that "sendButton" actually is "sendButtonText" and there is a prop that I can use to customize the input placeholder, that name is "inputPlaceHolder".

So it would be nice to update the docs according to these props. <3 

Also, thank you again for sharing this beautiful widget! 

Best regardsss

**Comment by ann0nip** [comment]
Thanks for your comments and the PR!

Cheers!
