### ISSUE TITLE
Closed div remains visible with opacity 0

### ISSUE THREAD

**Issue by Heldoe** [ann0nip/react-whatsapp-widget#4]
When the screen is closed the div remains there invisible, so I can't click on something under the invisible screen when it is closed.

**Comment by bre7** [comment]
Set `display` to `none` as default (or add new class).

https://github.com/ann0nip/react-whatsapp-widget/blob/master/src/components/App.js#L13
https://github.com/ann0nip/react-whatsapp-widget/blob/master/src/components/App.module.css#L14

**Comment by ann0nip** [comment]
Thanks for your contribution.
I used opacity instead of display due to the transition animation is not possible using the display property.
But, now it's fixed.
Thanks!
