### ISSUE TITLE
Weird style behavior on mobile

### ISSUE THREAD

**Issue by blackshot** [ann0nip/react-whatsapp-widget#6]
the container of the button is over the main page and it doesn't let me click everyrthing behind that leaving near 20% of the screen useless.

![imagen](https://user-images.githubusercontent.com/3688208/105084543-3e6df880-5a75-11eb-80fc-ca99c1a762e2.png)

**Comment by ann0nip** [comment]
Thanks! Tomorrow will be fixed.

**Comment by ann0nip** [comment]
My apologies all for the late push.
